audio/urls.py
from django.conf.urls import url

from . import views

app_name = "audio"
urlpatterns = [

    url(r'^audio$', views.audioView.as_view(), name='audio'),
]

nppower/urls.py
from django.conf.urls import url

from . import views,commit_view, onlogin_view

app_name = 'nppower'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^gdp$', views.GdpView.as_view(), name='gdp'),
    url(r'^race$', views.RaceView.as_view(), name='race'),
    url(r'^api/racelist$', commit_view.api_get_racelist, name='racejson'),
    url(r'^api/onlogin$', onlogin_view.create_session, name='csession'),
    url(r'^marathon/pacer$', views.PacerView.as_view(),name='pacer'),
    url(r'^marathon/post$', commit_view.post_race, name='post_race'),
    url(r'^marathon/delete$', commit_view.delete_race, name='delete_race'),
    
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

powerproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse
from nppower.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('nppower.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('audio.urls')),
    url(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')),
    url(r'^search/', include('haystack.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
]

templates/base.html
{% load staticfiles %}
{% load nppower_tags %}
{% load compress %}
<!DOCTYPE html>
<html>
<head>
    <title>机智未来</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- css -->
{% compress css %}
    <link rel="stylesheet" href="{% static 'nppower/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'nppower/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'nppower/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'nppower/css/highlights/github.css' %}">
    <style>
        span.highlighted {
            color: red;
        }
    </style>

{% endcompress %}
    <!-- js -->
{% compress js %}
    <script src="{% static 'nppower/js/jq-2.1.min.js' %}"></script>
    <script src="{% static 'nppower/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'nppower/js/pace.min.js' %}"></script>
    <script src="{% static 'nppower/js/modernizr.custom.js' %}"></script>
{% endcompress %}
    {% block head %} {% endblock head %}
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'nppower:index' %}"><b>未来能源网</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'nppower:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="/marathon/pacer" data-hover="马拉松配速计算器">马拉松配速</a></li>
                            <li class="cl-effect-11"><a href="/race" data-hover='参赛计划'>参赛计划</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <!--aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'nppower:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'nppower:category' category.pk %}">{{ category.name }} <span
                                        class="post-count">({{ category.num_posts }})</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'nppower:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                        {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>

                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside-->
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright"><a href="http://www.miitbeian.gov.cn/"
                                                        target="_blank" title="模板之家">粤ICP备17145082号-1 @深圳机智未来科技有限公司 All Right Reserved</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'nppower:index' %}">首页</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>
{% compress js%}
<script src="{% static 'nppower/js/script.js' %}"></script>
{% endcompress %}
</body>
</html>